# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_iHHhokqGnjO3N5soodOu6m2-C9T8FnE
"""

# save_model.py
import tensorflow as tf
from test_nlp_claims_project import SequentialModel

# Initialize the SequentialModel
output_dim = 1
model = SequentialModel(output_dim)

# Load model weights
model.load_weights('model_weights.h5')

# Save the model in the SavedModel format
model.save('saved_model/1')